/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeosEnergyRouteImport } from './routes/seos-energy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeosEnergyRoute = SeosEnergyRouteImport.update({
  id: '/seos-energy',
  path: '/seos-energy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/seos-energy': typeof SeosEnergyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/seos-energy': typeof SeosEnergyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/seos-energy': typeof SeosEnergyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/seos-energy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/seos-energy'
  id: '__root__' | '/' | '/seos-energy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeosEnergyRoute: typeof SeosEnergyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seos-energy': {
      id: '/seos-energy'
      path: '/seos-energy'
      fullPath: '/seos-energy'
      preLoaderRoute: typeof SeosEnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeosEnergyRoute: SeosEnergyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
